-- MySQL Script generated by MySQL Workbench
-- Wednesday 28 December 2022 12:50:36 AM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb4 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`log_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`log_in` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `User` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(50) NOT NULL,
  `Salary` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `test`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Question` (
  `QID` INT(11) NOT NULL,
  `Question` VARCHAR(500) NOT NULL,
  `Answer` VARCHAR(500) NOT NULL,
  `log_in_ID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`log_in_ID`),
  CONSTRAINT `fk_Question_log_in`
    FOREIGN KEY (`log_in_ID`)
    REFERENCES `test`.`log_in` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
